version: "3"
services:
  database:
    build: database
    environment:
      POSTGRES_DB: eth
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    container_name: project_db
    ports:
      - "5432"
  backend:
    build: backend
    environment: 
      PGHOST: project_db:5432
      PGDATABASE: eth
      PGUSER: test
      PGPASSWORD: test
    container_name: project_backend
    depends_on:
      - database
    ports:
      - "9999:8080"